#!/bin/bash

battery() {
    BAT=$(ls /sys/class/power_supply | grep BAT | head -n 1)
    
    # if has no batter
    if [[ -z $BAT ]]; then
        echo "101"
        exit 0
    fi
    
    cat /sys/class/power_supply/${BAT}/capacity
}
battery_stat() {
    BAT=$(ls /sys/class/power_supply | grep BAT | head -n 1)
    
    if [[ -z $BAT ]]; then
        echo "NO Battery"
        exit 0
    fi
    cat /sys/class/power_supply/${BAT}/status
}

if [[ "$1" == "--bat" ]]; then
    battery
    elif [[ "$1" == "--bat-st" ]]; then
    battery_stat
fi

