#!/bin/bash

EWW_BIN="eww"
LOCK_FILE_AUDIO="$HOME/.cache/eww-audio.lock"
LOCK_FILE_CALENDAR="$HOME/.cache/eww-calendar.lock"
LOCK_FILE_MEM="$HOME/.cache/eww-system.lock"
LOCK_FILE_SONG="$HOME/.cache/eww-song.lock"

close_everything() {
    ${EWW_BIN} close calendar system music_win audio_ctl
    rm -f "$LOCK_FILE_AUDIO" "$LOCK_FILE_CALENDAR" "$LOCK_FILE_MEM" "$LOCK_FILE_SONG"
}

calendar() {
    run() {
        close_everything
        ${EWW_BIN} open calendar --screen="$1"
        echo "$1" > "$LOCK_FILE_CALENDAR"
    }
    
    # Open widgets
    if [[ ! -f "$LOCK_FILE_CALENDAR" ]]; then
        run "$1" && echo "ok good!"
    else
        ${EWW_BIN} close calendar
        if [[ ! $(cat "$LOCK_FILE_CALENDAR") == "$1" ]]; then
            run "$1" && echo "ok good!"
        else
            rm "$LOCK_FILE_CALENDAR" && echo "closed"
        fi
    fi
}


system() {
    run() {
        close_everything
        ${EWW_BIN} open system --screen="$1"
        echo "$1" > "$LOCK_FILE_MEM"
    }
    
    # Open widgets
    if [[ ! -f "$LOCK_FILE_MEM" ]]; then
        run "$1" && echo "ok good!"
    else
        ${EWW_BIN} close system
        if [[ ! $(cat "$LOCK_FILE_MEM") == "$1" ]]; then
            run "$1" && echo "ok good!"
        else
            rm "$LOCK_FILE_MEM" && echo "closed"
        fi
    fi
}


music() {
    run() {
        close_everything
        ${EWW_BIN} open music_win --screen="$1"
        echo "$1" > "$LOCK_FILE_SONG"
    }
    
    # Open widgets
    if [[ ! -f "$LOCK_FILE_SONG" ]]; then
        run "$1" && echo "ok good!"
    else
        ${EWW_BIN} close music_win
        if [[ ! $(cat "$LOCK_FILE_SONG") == "$1" ]]; then
            run "$1" && echo "ok good!"
        else
            rm "$LOCK_FILE_SONG" && echo "closed"
        fi
        
    fi
}



audio() {
    run() {
        close_everything
        ${EWW_BIN} open audio_ctl --screen="$1"
        echo "$1" > "$LOCK_FILE_AUDIO"
    }
    
    # Open widgets
    if [[ ! -f "$LOCK_FILE_AUDIO" ]]; then
        
        run "$1" && echo "ok good!"
    else
        ${EWW_BIN} close audio_ctl
        if [[ ! $(cat "$LOCK_FILE_AUDIO") == "$1" ]]; then
            run "$1" && echo "ok good!"
        else
            rm "$LOCK_FILE_AUDIO" && echo "closed"
        fi
    fi
}

monitor=$1

if [ "$2" = "calendar" ]; then
    calendar "$monitor"
    elif [ "$2" = "system" ]; then
    system "$monitor"
    elif [ "$2" = "music" ]; then
    music "$monitor"
    elif [ "$2" = "audio" ]; then
    audio "$monitor"
fi
