#!/bin/zsh
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

#no category


#x-Server/qtile 
alias qtilelogs='cat ~/.local/share/qtile/qtile.log'
alias testqtile='export DISPLAY=:0 && Xephyr -br -ac -noreset -screen 800x600 :1 & export DISPLAY=:1&& qtile start -c ~/.config/qtile/WIP/config.py &'

#wayland (depricated)
alias sw='qtile start -b wayland'
alias sq='qtile start -b wayland'
alias fixbackground='nitrogen --restore'
alias testqtilewayland='qtile start -b wayland -c ~/.config/qtile/configWIP.py'

#default commands with better output/replacement
alias code='code --disable-gpu'


#Translate
alias transende="trans :de -s en"
alias transesde="trans :de -s es"
alias transdeen="trans :en -s de"
alias transdees="trans :es -s de"

#typos

#Brightnesctrl (depricated)
alias mbirght='brightness0'
alias mbright='brightness0'
alias mbright7='mbright .7'
alias blendet='python ~/.config/HomeassistantAPI_ctl/rollo.py'
alias brightness0="brightness DP-0" 
alias brightness1='brightness DVI-D-0'

#network debuging


#libre office
alias writer='libreoffice --writer'
alias calc='libreoffice --calc'

#alias rg='grep'

#file navigation (file/dir info)
alias valia='nvim ~/.config/bash/aliases && source ~/.config/bash/aliases'

#ssh
alias sshServer='myssh root@eis.lan.home'
alias eis='sshServer'
alias sshTu='ssh -Y sk76lufi@clientssh5.rbg.informatik.tu-darmstadt.de'
alias sshTuArm='ssh -Y sk76lufi@clientssh-arm.rbg.informatik.tu-darmstadt.de'

# pacman/AUR


# wacom tablett


if command -v xsetwacom > /dev/null; then
				alias getPadID="xsetwacom list | grep PAD | awk -F 'id: ' '{print \$2}' | awk -F ' ' '{print \$1}'"
				alias getStylousID="xsetwacom list | grep STYLUS | awk -F 'id: ' '{print \$2}' | awk -F ' ' '{print \$1}'"
				alias padMapScreen0='xsetwacom set $(getPadID) MapToOutput HEAD-0 && xsetwacom set $(getStylousID) MapToOutput HEAD-0'
				alias padMapScreen1='xsetwacom set $(getPadID) MapToOutput HEAD-1 && xsetwacom set $(getStylousID) MapToOutput HEAD-1'
				alias padMapScreen2='xsetwacom set $(getPadID) MapToOutput HEAD-2 && xsetwacom set $(getStylousID) MapToOutput HEAD-2'
fi





#alias +x='chmod +x'
#alias cleanHistory="awk '!x[\$0]++' < ~/.bash_history  > ~/.bash_history_c && \mv ~/.bash_history_c ~/.bash_history"
alias cShutdownUpdate="doas -- sh -c 'yes | paru -Scc && paru -Syu && shutdown now'"
#!/bin/bash

#no category
alias run='compgen -c | dmenu -i | bash'
alias s='sudo'

if command -v doas > /dev/null;
then
				alias s='doas'
				alias sudo='doas'
fi
alias smake='sudo make'

alias sx'=startx'

#default commands with better output/replacement
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"
alias mkdir="mkdir -pv"

#typos
alias vf='cd'
alias cod='code'
alias srouch='source'
alias sourch='source'
alias lö=ls

alias pingtest='ping heise.de'
alias testInternet='watch --interval .5 "ping -w 1 -c 1 heise.de | grep \"icmp_seq=1\" ; ping -w 1 -c 1 192.168.168.254 | grep \"icmp_seq=1\" ; ping -w 1 -c 1 192.168.169.254 | grep \"icmp_seq=1\" ; ping eis.lan.home -c 1 -w 1 | grep \"icmp_seq=1\" "'
alias getIp='curl -s http://checkip.dyndns.org/ | sed "s/[a-zA-Z<>/ :]//g"'

#alias rg='grep'
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
#file navigation (file/dir info)
if command -v ncdu > /dev/null 
then
alias treesize='ncdu --exclude /proc --exclude /mnt'
fi
alias folderSize='du -sh'
alias disksizes='df -h'
alias search="grep -rnw . -e"
alias findContent='grep -rnw '.' -e'
alias foldersize='du -ah --max-depth 1'
alias thissize='du -ah --max-depth 0'
alias cls='clear'

#ssh


# pacman/AUR
alias pacmanLog='cat /var/log/pacman.log'

alias sps='sp -S'
alias spyu='sp -Syu'
if command -v paru > /dev/null 
then
alias spfind='paru -Ql '
alias spq='paru -Q'
alias spqs='paru -Qs'
alias spss='paru -Ss'
alias yay='paru'
alias ys='yay -S'
alias yss='yay -Ss'
alias yr='yay -Rcns'
alias py='paru -Sy'
alias updateAll='paru -Syu'
alias spr='paru -Rcns'
alias spsyu='paru -Syu'
alias pu='paru -Syu'
alias sp='paru'
alias p='paru'
alias shutdownUpdate='paru -Syu && shutdown now'
fi
#cd/mkdir
alias ..='cd ..'
alias ...='cd ../..'
alias cd..='cd ..'

#ls/exa
if command -v exa >/dev/null
then
				alias ls='exa -g'
else 
				alias ls="ls --color=auto"
fi
alias sl='sudo ls -lha'
alias l='ls -lha'

# git
alias g='git'
alias gc='git commit'
alias gcm='git commit -m'
alias gp='git push'
alias gpu='git pull'
alias gpum='git pull --no-rebase --no-ff'
alias gpufop='git pull public master --no-rebase --no-ff'
alias ga='git add'
alias gr='git remote'
alias gsp='git stash && git pull && git stash pop' 

# vim
if command -v nvim > /dev/null
then
				alias vim="nvim"
fi

alias v='vim'
alias sv='s vim'
alias svim='sudo vim'

# Wireguard
alias startWG='doas systemctl start wg-quick@wg0 && sleep 1 && echo "your new IP addres is:" && getIp'
alias startWGlocal='doas systemctl start wg-quick@wg0-local-only && sleep 1 && ping eis.lan.home -c 1 | grep 64 || echo "could not ping home"'
alias stopWG='doas systemctl stop wg-quick@wg0 && sleep 1 && echo "your new IP addres is:" && getIp'
alias stopWGlocal='doas systemctl stop wg-quick@wg0-local-only && sleep 1 && ping eis.lan.home -c 1 && echo "seems to not be disabled or you are at home" || echo "disabled succesfully"'


alias aud='cd ~/Nextcloud/uni/AuD/'
alias aupl='cd ~/Nextcloud/uni/AuPl/'
alias mathe='cd ~/Nextcloud/uni/Mathe2/'
alias ro='cd ~/Nextcloud/uni/RO/'
alias fs1='cd ~/Nextcloud/uni/fs1/'

alias dark='xset dpms force off'
