#!/bin/bash

#no category
alias run='compgen -c | dmenu -i | bash'
if command -v doas > /dev/null;
then
				alias s='doas'
				alias sudo='doas'
fi
alias smake='sudo make'

alias sx'=startx'

#default commands with better output/replacement
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"
alias mkdir="mkdir -pv"

#typos
alias vf='cd'
alias cod='code'
alias srouch='source'
alias sourch='source'
alias lö=ls

alias pingtest='ping heise.de'
alias testInternet='watch --interval .5 "ping -w 1 -c 1 heise.de | grep \"icmp_seq=1\" ; ping -w 1 -c 1 192.168.168.254 | grep \"icmp_seq=1\" ; ping -w 1 -c 1 192.168.169.254 | grep \"icmp_seq=1\" ; ping eis.lan.home -c 1 -w 1 | grep \"icmp_seq=1\" "'
alias getIp='curl -s http://checkip.dyndns.org/ | sed "s/[a-zA-Z<>/ :]//g"'

#alias rg='grep'
alias find='fd'
alias config='/usr/bin/git --git-dir=/home/silas/.cfg/ --work-tree=/home/silas'

#file navigation (file/dir info)
if command -v ncdu > /dev/null then
alias treesize='ncdu --exclude /proc --exclude /mnt'
fi
alias folderSize='du -sh'
alias disksizes='df -h'
alias search="grep -rnw . -e"
alias findContent='grep -rnw '.' -e'
alias foldersize='du -ah --max-depth 1'
alias thissize='du -ah --max-depth 0'
alias cls='clear'

#ssh


# pacman/AUR
alias pacmanLog='cat /var/log/pacman.log'

alias sps='sp -S'
alias spyu='sp -Syu'
if command -v paru > /dev/null then
alias spfind='paru -Ql '
alias spq='paru -Q'
alias spqs='paru -Qs'
alias spss='paru -Ss'
alias yay='paru'
alias ys='yay -S'
alias yss='yay -Ss'
alias yr='yay -Rcns'
alias py='paru -Sy'
alias updateAll='paru -Syu'
alias spr='paru -Rcns'
alias spsyu='paru -Syu'
alias pu='paru -Syu'
alias sp='paru'
alias p='paru'
alias shutdownUpdate='paru -Syu && shutdown now'
fi
#cd/mkdir
alias ..='cd ..'
alias ...='cd ../..'
alias cd..='cd ..'

#ls/exa
if command -v exa >/dev/null
then
				alias ls='exa'
fi
alias sl='sudo ls -lhag'
alias l='ls -lhag'

# git
alias g='git'
alias gc='git commit'
alias gcm='git commit -m'
alias gp='git push'
alias gpu='git pull'
alias gpum='git pull --no-rebase --no-ff'
alias gpufop='git pull public master --no-rebase --no-ff'
alias ga='git add'
alias gr='git remote'
alias gsp='git stash && git pull && git stash pop' 

# vim
if command -v nvim > /dev/null
then
alias vim="nvim"
alias v='vim'
alias sv='s vim'
alias svim='sudo vim'
fi


# Wireguard
alias startWG='doas systemctl start wg-quick@wg0 && sleep 1 && echo "your new IP addres is:" && getIp'
alias stopWG='doas systemctl stop wg-quick@wg0 && sleep 1 && echo "your new IP addres is:" && getIp'

