#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPT_DIR/aliases-remoteable nvim exa doas

#no category


#x-Server/qtile 
alias qtilelogs='cat ~/.local/share/qtile/qtile.log'
alias testqtile='export DISPLAY=:0 && Xephyr -br -ac -noreset -screen 800x600 :1 & export DISPLAY=:1&& qtile start -c ~/.config/qtile/WIP/config.py &'

#wayland (depricated)
alias sw='qtile start -b wayland'
alias sq='qtile start -b wayland'
alias fixbackground='nitrogen --restore'
alias testqtilewayland='qtile start -b wayland -c ~/.config/qtile/configWIP.py'

#default commands with better output/replacement
alias code='code --disable-gpu'


#Translate
alias transende="trans :de -s en"
alias transesde="trans :de -s es"
alias transdeen="trans :en -s de"
alias transdees="trans :es -s de"

#typos

#Brightnesctrl (depricated)
alias mbirght='brightness0'
alias mbright='brightness0'
alias mbright7='mbright .7'
alias blendet='python ~/.config/HomeassistantAPI_ctl/rollo.py'
alias brightness0="brightness DP-0" 
alias brightness1='brightness DVI-D-0'

#network debuging


#libre office
alias writer='libreoffice --writer'
alias calc='libreoffice --calc'

#alias rg='grep'

#file navigation (file/dir info)
alias valia='nvim ~/.config/bash/aliases && source ~/.config/bash/aliases'

#ssh
alias sshServer='myssh root@eis.lan.home'
alias eis='sshServer'
alias sshTu='ssh -Y sk76lufi@clientssh5.rbg.informatik.tu-darmstadt.de'
alias sshTuArm='ssh -Y sk76lufi@clientssh-arm.rbg.informatik.tu-darmstadt.de'

# pacman/AUR


# wacom tablett
alias padMapScrenn0='xsetwacom set 14 MapToOutput HEAD-0'
alias padMapScrenn1='xsetwacom set 14 MapToOutput HEAD-1'
alias padMapScrenn2='xsetwacom set 14 MapToOutput HEAD-2'

#cd/mkdir

#ls/exa

# git

# vim

# Wireguard

alias +x='chmod +x'
alias cleanHistory="awk '!x[\$0]++' < ~/.bash_history  > ~/.bash_history_c && \mv ~/.bash_history_c ~/.bash_history"
alias cShutdownUpdate="doas -- sh -c 'yes | paru -Scc && paru -Syu && shutdown now'"
