#!/bin/bash
function brightness() {
	var=$2

	if (($(echo "$2>1" |bc -l) )); then	
	
		if (($(echo "$2<10" |bc -l) )); then	
				
			var=$(bc  <<< "scale=2;$var*10")
		fi
		var=$(bc  <<< "scale=2;$var/100")
	
	fi
	
	xrandr --output $1 --brightness $var
}
function md() {
	mkdir -pv $1 && cd $1
}

function palias(){
	echo "alias $1='$2'" >> ~/.config/bash/aliases && source ~/.config/bash/aliases;
}

function dot() {
		config -C $HOME ls-tree -r master --name-only | fzf --preview "highlight -i $HOME/{1} --stdout --out-format=ansi -q --force"| sed "s@^@$HOME/@" | xargs -ro "$EDITOR"
}

function sw() {
	kanshi
	setxkbmap de &
	clipmanager &
	sxhkd &
	udiskie --tray &
	numlockx &
	nitrogen --restore &
	qtile start -b wayland

}
# re-wrote the script above
bind '"\C-r": "\C-x1\e^\er"'
bind -x '"\C-x1": __fzf_history';

__fzf_history () {
				__ehc $(history | fzf --tac --tiebreak=index | perl -ne 'm/^\s*([0-9]+)/ and print "!$1"')
}

__ehc() {
				if [[ -n $1 ]]
				then
								bind '"\er": redraw-current-line'
								bind '"\e^": magic-space'
								READLINE_LINE=${READLINE_LINE:+${READLINE_LINE:0:READLINE_POINT}}${1}${READLINE_LINE:+${READLINE_LINE:READLINE_POINT}}
								READLINE_POINT=$(( READLINE_POINT + ${#1} ))
				else
								bind '"\er":'
								bind '"\e^":'
				fi
}



function c() {
				newPath=$(exa -lhaa --color always | fzf --multi --ansi --preview "exa -lha {7..}" | awk '{ s = ""; for (i = 7; i <= NF; i++) s = s $i " "; print s }' )
				if [ ! -z "$newPath" ]
				then
								cd "$newPath"
								c
				fi	
}

function pi()
{
    paru -Sl | awk '{print $2($4=="" ? "" : "*")}' | fzf --multi --preview 'echo {1} | tr -d "*" | xargs -r paru -Si' | tr -d "*" | xargs -ro paru -S
}
function pd()
{
    paru -Qq | fzf --multi --preview 'paru -Qi {1}' | xargs -ro paru -Rncs
}
