# Inserts a blank line between shell prompts
add_newline = false

format = """
($status$cmd_duration
)$fill${custom.kernal}$shell:$time$memory_usage
$all
"""

#right_format = """                                          \
#${custom.kernal}$shell:$time$memory_usage"""

[fill]
symbol = " "

[status]
disabled = false
map_symbol = true
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '

[git_branch]
symbol = " "
[time]
disabled = false

[git_metrics]
disabled = false

[git_commit]
disabled = false
tag_disabled=false
only_detached=false
tag_symbol = '🔖 '
tag_max_candidates = 2

[custom.kernal]
when = true
command = "uname -r"
format = "$output: "

[custom.timetrace]
command = """ timetrace status --format "{project}:{trackedTimeToday}" """
when = """ timetrace status --output json | grep -P '\"trackedTimeCurrent\": \"(?!-)' """
shell = "sh"

[custom.klog]
command = """${HOME}/.local/script/klog_running_record.sh"""
when = """ ${HOME}/.local/script/klog_running_record.sh | grep -q '.'"""
shell = "sh"
format= "[⏱️ $output](blue bold)"

[shell]
zsh_indicator = "%_"
fish_indicator = ''
bash_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false

[memory_usage]
disabled = false
format = "ram: $ram_pct swp: $swap_pct"

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false


[cmd_duration]
show_milliseconds = true


[directory]
truncation_length = 0
truncation_symbol = '…/'
truncate_to_repo = false

[jobs]
disabled = false 
#symbol = 'TEST 123'
number_threshold = 2 
symbol_threshold = 1


#[localip]
#ssh_only = false
#format = '@[$localipv4](bold red) '
#disabled = false



[gradle]
symbol = " "
[kotlin]
symbol = " "

[java]
style = 'red'
symbol = ' '

[python]
style = "fg:76"
symbol = " "

[golang]
symbol = "󰟓 "

[rust]
symbol = "󱘗 "

[haskell]
symbol = "󰲒 "

[nodejs]
symbol = "󰌞 "

