[ids]

*

[main]

capslock = overload(capslock, esc)

[capslock]

' = macro(capslock+')
, = macro(capslock+,)
- = macro(capslock+-)
. = macro(capslock+.)
/ = macro(capslock+/)
1 = macro(capslock+1)
2 = macro(capslock+2)
3 = macro(capslock+3)
4 = macro(capslock+4)
5 = macro(capslock+5)
6 = macro(capslock+6)
7 = macro(capslock+7)
8 = macro(capslock+8)
9 = macro(capslock+9)
; = macro(capslock+;)
[ = macro(capslock+[)
\ = macro(capslock+\)
] = macro(capslock+])
a = macro(capslock+a)
b = macro(capslock+b)
c = macro(capslock+c)
d = macro(capslock+d)
e = macro(capslock+e)
f = macro(capslock+f)
g = macro(capslock+g)
h = macro(capslock+h)
i = macro(capslock+i)
j = macro(capslock+j)
k = macro(capslock+k)
l = macro(capslock+l)
m = macro(capslock+m)
n = macro(capslock+n)
o = macro(capslock+o)
p = macro(capslock+p)
q = macro(capslock+q)
r = macro(capslock+r)
s = macro(capslock+s)
t = macro(capslock+t)
u = macro(capslock+u)
v = macro(capslock+v)
w = macro(capslock+w)
x = macro(capslock+x)
y = macro(capslock+y)
z = macro(capslock+z)

shift = macro(capslock+shift)
altgr = macro(capslock+altgr)
